apiVersion: secretgenerator.mittwald.de/v1alpha1
kind: TemplateSecret
metadata:
  name: example-templatesecret
spec:
  data:
    - config.yaml: |
        value1: {{ .value }}
  field:
    - fieldName: value
      encoding: raw
      length: 10
